### PR TITLE
Update controller to follow light level in RGB

### PR DESCRIPTION
**Pull request by ossgeek314**
Reduction in level results in changing of RGB values

### CODE REVIEW

**Review by erocm123 — COMMENTED** [review]
So just a few things. In the SmartThings IDE you don't need to explicitly declare any attribute that is not a custom attribute. So you can remove all the attributes you added. Also, "state" variables are not really attributes and don't need to be declared (so you can remove those).

One thing that I am noticing is that adjusting the level does not produce what I am thinking (perhaps that is the meaning of your comment). For example, if I have blue set to 100% and nothing else, I would expect the main level slider to only adjust blue. For some reason it is adjusting other values.

I am testing your huesatToRGB method though and it seems to be working really well.

**Comment by ossgeek314** [comment]
I see that now.  I didn't test the use of individual R, G, B scales... just the color picker and google voice.  The algo depends on knowing the "original" color before dimming.  the R, G, B only functions don't change that variable.  

Let me add that functionality and see if it works more as expected.

**Comment by erocm123** [comment]
I borrowed your huesatToRGB method and put it in master (with credit to you of course). Hope you don't mind. I see that you have added more changes to it. What is the difference? 

I am also testing your latest commit. I am still seeing strange behavior when adjusting the main level slider. If I set red to 50% (only color) and adjust the main slider, users are going to expect only red to adjust. Seems RGB are all changing in that scenario.

**Comment by ossgeek314** [comment]
I just made an overloaded function call.  Basically, if you call the huesatToRGB function without a V (level) it uses the default level of 1.0 (100).  

I just tested for me and I'm not seeing this behavior.  If I set the color red, or adjust the sliders to only be red... then change the brightness level, only the red color is altered (as RGB does not actually have a brightness level control, the RGB->HSV function gets the hue sat and then sets it with the new brightness... this will alter the RGB color).  But if you I only have red turned on... only red gets moved by the brightness.

It basically works exactly like this tool: http://colorizer.org/

Where if you select colors... then change the "V" in the HSV, it changes the RGB to match the new HSV values.  It is basically trying to get around the fact that RGB does not store a "brightness" level in the hex but that brightness can be hidden in the HSV.

Does any of this make sense?

**Comment by ossgeek314** [comment]
closing pull to resolve conflics

**Comment by erocm123** [comment]
Strange, the colorizer tool works as expected. Maybe I grabbed the wrong pull request. Do you have the code you can put on https://pastebin.com/?

I am very interested in looking into it further.

**Comment by ossgeek314** [comment]
For sure... I've been working on other things within it as well.  Let me clean up some code and do some slight debugging then get the link up.  I think the issue might be the psuedoColor initial state... but maybe not :)

**Pull request closed without merging**
