### PR TITLE
Fixed the relay toggle and fixed a few things for IPv6

### PR DESCRIPTION
**Pull request by cjcharles0**
Had to tweak a bit to deal with IPv6 support which is added to the ESP libraries

### CODE REVIEW

**Comment by erocm123** [comment]
I think you asked if I was using an interrupt for the button presses and I forgot to answer. The answer is yes.

Looking at your change it looks like you are getting rid of the reset method of holding down the j3 button for 20 or 30 seconds. Is that causing problems with your change?

**Comment by cjcharles0** [comment]
Your question made me realise my commit had an old version with the button_down and button_up actions swapped around.

I havent removed the press and hold feature, but I have changed it so that they are checked on button release, rather than button press - this is what you intended I think.

I did tweak it so it is 10-30s and 30-60s hold for the two actions, rather than 10-20 and 20-60.

**Comment by cjcharles0** [comment]
FFS, Im not sure what is going on with my github versioning. Sorry!

I think Im finally there and have tested the updated code properly now aswell.

**Comment by cjcharles0** [comment]
FFS, Im not sure what is going on with my github versioning. Sorry!

I think Im finally there and have tested the updated code properly now aswell.

**Pull request merged**
